PKG_NAME    = sqisign3
PKG_URL     = https://github.com/gbanegas/sqisign_verify_lvl3
PKG_VERSION = 8ebf0306306bde9af1d8613930aa9aa15d54d6e4
PKG_LICENSE = MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)/ -f $(CURDIR)/Makefile.sqisign
