PKG_NAME    = sqisign
PKG_URL     = https://github.com/gbanegas/sqisign_verify
PKG_VERSION = 2de4bd6503171d0a4aff12de13f2607d9d7efc16
PKG_LICENSE = MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)/ -f $(CURDIR)/Makefile.sqisign
